---
- name: uninstall python-pip from apt
  apt:
    name: python-pip
    state: absent
  sudo: yes
- name: install easy_install
  apt:
    name: python-setuptools
    state: present
  sudo: yes
- name: install pip via easy_install
  easy_install:
    name: pip
  sudo: yes
