---
- name: add docker key
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: yes
- name: add docker ppa
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
  sudo: yes
- name: install docker-py
  pip:
    name: docker-py
  sudo: yes
- name: install docker from ppa
  apt:
    name: lxc-docker
    state: present
  sudo: yes
